# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GabbioniUi.ui'
#
# Created: Sun Nov 30 10:43:43 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(798, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.horizontalLayout.addWidget(self.mplwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/document-open-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/document-new-6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRationalMethod = QtGui.QAction(MainWindow)
        self.actionRationalMethod.setObjectName(_fromUtf8("actionRationalMethod"))
        self.actionHighWaterMarks = QtGui.QAction(MainWindow)
        self.actionHighWaterMarks.setObjectName(_fromUtf8("actionHighWaterMarks"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/document-properties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNewProject = QtGui.QAction(MainWindow)
        self.actionNewProject.setObjectName(_fromUtf8("actionNewProject"))
        self.actionSimpleDesign = QtGui.QAction(MainWindow)
        self.actionSimpleDesign.setObjectName(_fromUtf8("actionSimpleDesign"))
        self.actionStepByStepDesign = QtGui.QAction(MainWindow)
        self.actionStepByStepDesign.setObjectName(_fromUtf8("actionStepByStepDesign"))
        self.actionLayerByLayerDesign = QtGui.QAction(MainWindow)
        self.actionLayerByLayerDesign.setObjectName(_fromUtf8("actionLayerByLayerDesign"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionSimpleDesign)
        self.menuTools.addAction(self.actionLayerByLayerDesign)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Gabbioni", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionRationalMethod.setText(_translate("MainWindow", "Rational method", None))
        self.actionHighWaterMarks.setText(_translate("MainWindow", "High water marks", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1", None))
        self.actionNewProject.setText(_translate("MainWindow", "New Project", None))
        self.actionSimpleDesign.setText(_translate("MainWindow", "&Simple design", None))
        self.actionSimpleDesign.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionStepByStepDesign.setText(_translate("MainWindow", "Step by step design", None))
        self.actionLayerByLayerDesign.setText(_translate("MainWindow", "Layer by layer design", None))


class Ui_SimpleDesign(object):
    def setupUi(self, SimpleDesign):
        SimpleDesign.setObjectName(_fromUtf8("SimpleDesign"))
        SimpleDesign.resize(423, 236)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SimpleDesign)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(SimpleDesign)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRunoff = QtGui.QWidget()
        self.tabRunoff.setObjectName(_fromUtf8("tabRunoff"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabRunoff)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tabRunoff)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runoff = QtGui.QLineEdit(self.tabRunoff)
        self.runoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoff.setObjectName(_fromUtf8("runoff"))
        self.horizontalLayout.addWidget(self.runoff)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.tabRunoff)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.runoffRationalFormula = QtGui.QPushButton(self.tabRunoff)
        self.runoffRationalFormula.setObjectName(_fromUtf8("runoffRationalFormula"))
        self.gridLayout_3.addWidget(self.runoffRationalFormula, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.runoffWaterMarks = QtGui.QPushButton(self.tabRunoff)
        self.runoffWaterMarks.setObjectName(_fromUtf8("runoffWaterMarks"))
        self.gridLayout_3.addWidget(self.runoffWaterMarks, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabRunoff, _fromUtf8(""))
        self.tabDimensions = QtGui.QWidget()
        self.tabDimensions.setObjectName(_fromUtf8("tabDimensions"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabDimensions)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.tabDimensions)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.weirLayersHeight = QtGui.QComboBox(self.tabDimensions)
        self.weirLayersHeight.setObjectName(_fromUtf8("weirLayersHeight"))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.weirLayersHeight, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabDimensions)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        self.bodyLayersHeight = QtGui.QComboBox(self.tabDimensions)
        self.bodyLayersHeight.setObjectName(_fromUtf8("bodyLayersHeight"))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.bodyLayersHeight, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(self.tabDimensions)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.abutmentEqual = QtGui.QRadioButton(self.groupBox)
        self.abutmentEqual.setChecked(True)
        self.abutmentEqual.setObjectName(_fromUtf8("abutmentEqual"))
        self.verticalLayout_6.addWidget(self.abutmentEqual)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.abutmentCustom = QtGui.QRadioButton(self.groupBox)
        self.abutmentCustom.setObjectName(_fromUtf8("abutmentCustom"))
        self.horizontalLayout_3.addWidget(self.abutmentCustom)
        self.abutmentValue = QtGui.QLineEdit(self.groupBox)
        self.abutmentValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abutmentValue.sizePolicy().hasHeightForWidth())
        self.abutmentValue.setSizePolicy(sizePolicy)
        self.abutmentValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.abutmentValue.setObjectName(_fromUtf8("abutmentValue"))
        self.horizontalLayout_3.addWidget(self.abutmentValue)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabDimensions, _fromUtf8(""))
        self.tabWeir = QtGui.QWidget()
        self.tabWeir.setObjectName(_fromUtf8("tabWeir"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWeir)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabWeir)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.weirLenght = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirLenght.sizePolicy().hasHeightForWidth())
        self.weirLenght.setSizePolicy(sizePolicy)
        self.weirLenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirLenght.setObjectName(_fromUtf8("weirLenght"))
        self.gridLayout.addWidget(self.weirLenght, 0, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabWeir)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.weirCoefficient = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirCoefficient.sizePolicy().hasHeightForWidth())
        self.weirCoefficient.setSizePolicy(sizePolicy)
        self.weirCoefficient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirCoefficient.setObjectName(_fromUtf8("weirCoefficient"))
        self.gridLayout.addWidget(self.weirCoefficient, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 3, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabWeir)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.waterLevel = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterLevel.sizePolicy().hasHeightForWidth())
        self.waterLevel.setSizePolicy(sizePolicy)
        self.waterLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.waterLevel.setObjectName(_fromUtf8("waterLevel"))
        self.gridLayout.addWidget(self.waterLevel, 2, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 2, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabWeir)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.weirHeight = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirHeight.sizePolicy().hasHeightForWidth())
        self.weirHeight.setSizePolicy(sizePolicy)
        self.weirHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirHeight.setObjectName(_fromUtf8("weirHeight"))
        self.gridLayout.addWidget(self.weirHeight, 3, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 3, 3, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabWeir)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.weirLayers = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirLayers.sizePolicy().hasHeightForWidth())
        self.weirLayers.setSizePolicy(sizePolicy)
        self.weirLayers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirLayers.setObjectName(_fromUtf8("weirLayers"))
        self.gridLayout.addWidget(self.weirLayers, 4, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 4, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tabWeir, _fromUtf8(""))
        self.tabStructural = QtGui.QWidget()
        self.tabStructural.setObjectName(_fromUtf8("tabStructural"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabStructural)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_10 = QtGui.QLabel(self.tabStructural)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.specWater = QtGui.QLineEdit(self.tabStructural)
        self.specWater.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.specWater.setObjectName(_fromUtf8("specWater"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.specWater)
        self.label_11 = QtGui.QLabel(self.tabStructural)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.specRock = QtGui.QLineEdit(self.tabStructural)
        self.specRock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.specRock.setObjectName(_fromUtf8("specRock"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.specRock)
        self.label_12 = QtGui.QLabel(self.tabStructural)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.frictionFactor = QtGui.QLineEdit(self.tabStructural)
        self.frictionFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionFactor.setObjectName(_fromUtf8("frictionFactor"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frictionFactor)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tabStructural, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SimpleDesign)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.runoff)
        self.label_2.setBuddy(self.runoffRationalFormula)
        self.label_7.setBuddy(self.weirLayersHeight)
        self.label_8.setBuddy(self.bodyLayersHeight)
        self.label_3.setBuddy(self.weirLenght)
        self.label_4.setBuddy(self.weirCoefficient)
        self.label_6.setBuddy(self.waterLevel)
        self.label_5.setBuddy(self.weirHeight)
        self.label_9.setBuddy(self.weirLayers)

        self.retranslateUi(SimpleDesign)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SimpleDesign.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SimpleDesign.reject)
        QtCore.QMetaObject.connectSlotsByName(SimpleDesign)

    def retranslateUi(self, SimpleDesign):
        SimpleDesign.setWindowTitle(_translate("SimpleDesign", "Simple Design", None))
        self.label.setText(_translate("SimpleDesign", "<html><head/><body><p>Runoff &amp;value [m<span style=\" vertical-align:super;\">3</span> s<span style=\" vertical-align:super;\">-1</span>]:</p></body></html>", None))
        self.label_2.setText(_translate("SimpleDesign", "Methods for runoff calculation:", None))
        self.runoffRationalFormula.setText(_translate("SimpleDesign", "Rational &formula", None))
        self.runoffWaterMarks.setText(_translate("SimpleDesign", "&High Water Marks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRunoff), _translate("SimpleDesign", "&Runoff", None))
        self.label_7.setText(_translate("SimpleDesign", "&Weir layers height [m]:", None))
        self.weirLayersHeight.setItemText(0, _translate("SimpleDesign", "0.15", None))
        self.weirLayersHeight.setItemText(1, _translate("SimpleDesign", "0.20", None))
        self.weirLayersHeight.setItemText(2, _translate("SimpleDesign", "0.30", None))
        self.weirLayersHeight.setItemText(3, _translate("SimpleDesign", "0.50", None))
        self.weirLayersHeight.setItemText(4, _translate("SimpleDesign", "1.00", None))
        self.label_8.setText(_translate("SimpleDesign", "&Dam body layers height [m]:", None))
        self.bodyLayersHeight.setItemText(0, _translate("SimpleDesign", "0.15", None))
        self.bodyLayersHeight.setItemText(1, _translate("SimpleDesign", "0.20", None))
        self.bodyLayersHeight.setItemText(2, _translate("SimpleDesign", "0.30", None))
        self.bodyLayersHeight.setItemText(3, _translate("SimpleDesign", "0.50", None))
        self.bodyLayersHeight.setItemText(4, _translate("SimpleDesign", "1.00", None))
        self.groupBox.setTitle(_translate("SimpleDesign", "Abutments", None))
        self.abutmentEqual.setText(_translate("SimpleDesign", "Abutment equal to layers height", None))
        self.abutmentCustom.setText(_translate("SimpleDesign", "Custom value [m]:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDimensions), _translate("SimpleDesign", "&Dimensions", None))
        self.label_3.setText(_translate("SimpleDesign", "&Lenght [m]:", None))
        self.label_4.setText(_translate("SimpleDesign", "&Coefficient:", None))
        self.weirCoefficient.setText(_translate("SimpleDesign", "1.45", None))
        self.label_6.setText(_translate("SimpleDesign", "W&ater level [m]:", None))
        self.label_5.setText(_translate("SimpleDesign", "&Height [m]:", None))
        self.label_9.setText(_translate("SimpleDesign", "La&yers:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWeir), _translate("SimpleDesign", "&Weir", None))
        self.label_10.setText(_translate("SimpleDesign", "<html><head/><body><p>Specific weight of water with sediment [t m<span style=\" vertical-align:super;\">-3</span>]:</p></body></html>", None))
        self.specWater.setText(_translate("SimpleDesign", "1.2", None))
        self.label_11.setText(_translate("SimpleDesign", "<html><head/><body><p>Specific weight of rock [t m<span style=\" vertical-align:super;\">-3</span>]:</p></body></html>", None))
        self.specRock.setText(_translate("SimpleDesign", "2.4", None))
        self.label_12.setText(_translate("SimpleDesign", "Rock on rock friction factor:", None))
        self.frictionFactor.setText(_translate("SimpleDesign", "0.75", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStructural), _translate("SimpleDesign", "&Structural Analysis", None))


class Ui_RationalMethod(object):
    def setupUi(self, RationalMethod):
        RationalMethod.setObjectName(_fromUtf8("RationalMethod"))
        RationalMethod.resize(357, 230)
        self.verticalLayout_3 = QtGui.QVBoxLayout(RationalMethod)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(RationalMethod)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelRunoffCoefficient = QtGui.QLabel(self.groupBox_2)
        self.labelRunoffCoefficient.setObjectName(_fromUtf8("labelRunoffCoefficient"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRunoffCoefficient)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.runoffCoefficient = QtGui.QLineEdit(self.groupBox_2)
        self.runoffCoefficient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoffCoefficient.setObjectName(_fromUtf8("runoffCoefficient"))
        self.horizontalLayout_3.addWidget(self.runoffCoefficient)
        self.getCoefficientButton = QtGui.QToolButton(self.groupBox_2)
        self.getCoefficientButton.setObjectName(_fromUtf8("getCoefficientButton"))
        self.horizontalLayout_3.addWidget(self.getCoefficientButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.labelRainFallIntensity = QtGui.QLabel(self.groupBox_2)
        self.labelRainFallIntensity.setObjectName(_fromUtf8("labelRainFallIntensity"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelRainFallIntensity)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.rainfallIntensity = QtGui.QLineEdit(self.groupBox_2)
        self.rainfallIntensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rainfallIntensity.setObjectName(_fromUtf8("rainfallIntensity"))
        self.horizontalLayout_2.addWidget(self.rainfallIntensity)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.labelArea = QtGui.QLabel(self.groupBox_2)
        self.labelArea.setObjectName(_fromUtf8("labelArea"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.watershedArea = QtGui.QLineEdit(self.groupBox_2)
        self.watershedArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.watershedArea.setObjectName(_fromUtf8("watershedArea"))
        self.horizontalLayout.addWidget(self.watershedArea)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(RationalMethod)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelRunoff = QtGui.QLabel(self.groupBox_4)
        self.labelRunoff.setObjectName(_fromUtf8("labelRunoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRunoff)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.runoff = QtGui.QLineEdit(self.groupBox_4)
        self.runoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoff.setObjectName(_fromUtf8("runoff"))
        self.horizontalLayout_8.addWidget(self.runoff)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.buttonBox = QtGui.QDialogButtonBox(RationalMethod)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.labelRunoffCoefficient.setBuddy(self.runoffCoefficient)
        self.labelRainFallIntensity.setBuddy(self.rainfallIntensity)
        self.labelArea.setBuddy(self.watershedArea)
        self.labelRunoff.setBuddy(self.runoff)

        self.retranslateUi(RationalMethod)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RationalMethod.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RationalMethod.reject)
        QtCore.QMetaObject.connectSlotsByName(RationalMethod)

    def retranslateUi(self, RationalMethod):
        RationalMethod.setWindowTitle(_translate("RationalMethod", "Rational Formula", None))
        self.groupBox_2.setTitle(_translate("RationalMethod", "Rational formula", None))
        self.labelRunoffCoefficient.setText(_translate("RationalMethod", "Runoff &Coefficient:", None))
        self.getCoefficientButton.setText(_translate("RationalMethod", "...", None))
        self.labelRainFallIntensity.setText(_translate("RationalMethod", "<html><head/><body><p>&amp;Intensity [mm h<span style=\" vertical-align:super;\">-1</span>]:</p></body></html>", None))
        self.labelArea.setText(_translate("RationalMethod", "&Area [ha]:", None))
        self.groupBox_4.setTitle(_translate("RationalMethod", "Runoff", None))
        self.labelRunoff.setText(_translate("RationalMethod", "<html><head/><body><p>&amp;Runoff [m<span style=\" vertical-align:super;\">3</span> s<span style=\" vertical-align:super;\">-1</span>]:</p></body></html>", None))

class Ui_AboutDlg(object):
    def setupUi(self, AboutDlg):
        AboutDlg.setObjectName(_fromUtf8("AboutDlg"))
        AboutDlg.resize(414, 221)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/document-properties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDlg.setWindowIcon(icon)
        AboutDlg.setSizeGripEnabled(True)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(AboutDlg)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(AboutDlg)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(AboutDlg)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(AboutDlg)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(AboutDlg)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(AboutDlg)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(AboutDlg)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton = QtGui.QPushButton(AboutDlg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-delete-6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(AboutDlg)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("pressed()")), AboutDlg.close)
        QtCore.QMetaObject.connectSlotsByName(AboutDlg)

    def retranslateUi(self, AboutDlg):
        AboutDlg.setWindowTitle(_translate("AboutDlg", "About..", None))
        self.label.setText(_translate("AboutDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Gabbioni</span></p></body></html>", None))
        self.label_6.setText(_translate("AboutDlg", "<html><head/><body><p><span style=\" font-style:italic;\">version 0.1</span></p></body></html>", None))
        self.label_2.setText(_translate("AboutDlg", "<html><head/><body><p><span style=\" font-style:italic;\">Gabion dams design program.</span></p></body></html>", None))
        self.label_3.setText(_translate("AboutDlg", "Copyright © 2014-2016 Eduardo Jiménez", None))
        self.label_5.setText(_translate("AboutDlg", "<html><head/><body><p>More information at: <a href=\"http://www.irriapps.com/gabbioni/\"><span style=\" text-decoration: underline; color:#0057ae;\">http://www.irriapps.com/gabbioni/</span></a></p></body></html>", None))
        self.label_4.setText(_translate("AboutDlg", "The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.", None))
        self.pushButton.setText(_translate("AboutDlg", "&Close", None))


class Ui_RunoffCoefficient(object):
    def setupUi(self, RunoffCoefficient):
        RunoffCoefficient.setObjectName(_fromUtf8("RunoffCoefficient"))
        RunoffCoefficient.setWindowModality(QtCore.Qt.NonModal)
        RunoffCoefficient.resize(500, 450)
        RunoffCoefficient.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(RunoffCoefficient)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(RunoffCoefficient)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtGui.QLabel(RunoffCoefficient)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtGui.QTableWidget(RunoffCoefficient)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(17)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(RunoffCoefficient)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.annualPrecipitation = QtGui.QLineEdit(RunoffCoefficient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annualPrecipitation.sizePolicy().hasHeightForWidth())
        self.annualPrecipitation.setSizePolicy(sizePolicy)
        self.annualPrecipitation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.annualPrecipitation.setObjectName(_fromUtf8("annualPrecipitation"))
        self.gridLayout.addWidget(self.annualPrecipitation, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(RunoffCoefficient)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 2)
        self.runoffCoefficient = QtGui.QLineEdit(RunoffCoefficient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runoffCoefficient.sizePolicy().hasHeightForWidth())
        self.runoffCoefficient.setSizePolicy(sizePolicy)
        self.runoffCoefficient.setFrame(True)
        self.runoffCoefficient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoffCoefficient.setReadOnly(True)
        self.runoffCoefficient.setObjectName(_fromUtf8("runoffCoefficient"))
        self.gridLayout.addWidget(self.runoffCoefficient, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(RunoffCoefficient)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RunoffCoefficient)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RunoffCoefficient.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RunoffCoefficient.reject)
        QtCore.QMetaObject.connectSlotsByName(RunoffCoefficient)

    def retranslateUi(self, RunoffCoefficient):
        RunoffCoefficient.setWindowTitle(_translate("RunoffCoefficient", "Runoff coefficient", None))
        self.label_5.setText(_translate("RunoffCoefficient", "Select a runoff coefficient from the table:", None))
        self.label.setText(_translate("RunoffCoefficient", "<html><head/><body><p><span style=\" font-weight:600;\">A</span>) Permeable soil; <span style=\" font-weight:600;\">B</span>) Semi-permeable soil; <span style=\" font-weight:600;\">C</span>) Almost impermeable soil</p></body></html>", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("RunoffCoefficient", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("RunoffCoefficient", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("RunoffCoefficient", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("RunoffCoefficient", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("RunoffCoefficient", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("RunoffCoefficient", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("RunoffCoefficient", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("RunoffCoefficient", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("RunoffCoefficient", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("RunoffCoefficient", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("RunoffCoefficient", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("RunoffCoefficient", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("RunoffCoefficient", "13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("RunoffCoefficient", "14", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("RunoffCoefficient", "15", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("RunoffCoefficient", "16", None))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("RunoffCoefficient", "17", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RunoffCoefficient", "Land use", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RunoffCoefficient", "A", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RunoffCoefficient", "B", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RunoffCoefficient", "C", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("RunoffCoefficient", "Barbecho, áreas incultas y desnudas", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("RunoffCoefficient", "Cultivos:", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("RunoffCoefficient", "En hilera", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("RunoffCoefficient", "Legumbres o rotación de pradera", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("RunoffCoefficient", "Granos pequeños", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("RunoffCoefficient", "Pastizal (Porcentaje del suelo cubierto o pastoreo):", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("RunoffCoefficient", "Más del 75 % (Poco)", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("RunoffCoefficient", " 0.14", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("RunoffCoefficient", " 0.20", None))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("RunoffCoefficient", "Del 50 al 75 % (Regular)", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("RunoffCoefficient", " 0.20", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("RunoffCoefficient", "Menos del 50 % (Excesivo)", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("RunoffCoefficient", "Bosque:", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto más del 75 %", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("RunoffCoefficient", " 0.07", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("RunoffCoefficient", " 0.16", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto del 50 al 75 %", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("RunoffCoefficient", " 0.12", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("RunoffCoefficient", " 0.22", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto del 25 al 50 %", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("RunoffCoefficient", " 0.17", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto menos del 25 %", None))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("RunoffCoefficient", " 0.22", None))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("RunoffCoefficient", "Zonas urbanas", None))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("RunoffCoefficient", " 0.29", None))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("RunoffCoefficient", " 0.32", None))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("RunoffCoefficient", "Caminos", None))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("RunoffCoefficient", " 0.33", None))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("RunoffCoefficient", "Pradera permanente", None))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("RunoffCoefficient", " 0.18", None))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("RunoffCoefficient", "0.30", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("RunoffCoefficient", "Annual precipitation [mm]:", None))
        self.label_4.setText(_translate("RunoffCoefficient", "Runoff coefficient value:", None))


import resources
from matplotlibwidget import MatplotlibWidget
