# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunoffCoefficient.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RunoffCoefficient(object):
    def setupUi(self, RunoffCoefficient):
        RunoffCoefficient.setObjectName(_fromUtf8("RunoffCoefficient"))
        RunoffCoefficient.setWindowModality(QtCore.Qt.NonModal)
        RunoffCoefficient.resize(500, 450)
        RunoffCoefficient.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(RunoffCoefficient)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(RunoffCoefficient)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtGui.QLabel(RunoffCoefficient)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtGui.QTableWidget(RunoffCoefficient)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(17)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(RunoffCoefficient)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.annualPrecipitation = QtGui.QLineEdit(RunoffCoefficient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annualPrecipitation.sizePolicy().hasHeightForWidth())
        self.annualPrecipitation.setSizePolicy(sizePolicy)
        self.annualPrecipitation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.annualPrecipitation.setObjectName(_fromUtf8("annualPrecipitation"))
        self.gridLayout.addWidget(self.annualPrecipitation, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(RunoffCoefficient)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 2)
        self.runoffCoefficient = QtGui.QLineEdit(RunoffCoefficient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runoffCoefficient.sizePolicy().hasHeightForWidth())
        self.runoffCoefficient.setSizePolicy(sizePolicy)
        self.runoffCoefficient.setFrame(True)
        self.runoffCoefficient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoffCoefficient.setReadOnly(True)
        self.runoffCoefficient.setObjectName(_fromUtf8("runoffCoefficient"))
        self.gridLayout.addWidget(self.runoffCoefficient, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(RunoffCoefficient)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RunoffCoefficient)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RunoffCoefficient.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RunoffCoefficient.reject)
        QtCore.QMetaObject.connectSlotsByName(RunoffCoefficient)

    def retranslateUi(self, RunoffCoefficient):
        RunoffCoefficient.setWindowTitle(_translate("RunoffCoefficient", "Runoff coefficient", None))
        self.label_5.setText(_translate("RunoffCoefficient", "Select a runoff coefficient from the table:", None))
        self.label.setText(_translate("RunoffCoefficient", "<html><head/><body><p><span style=\" font-weight:600;\">A</span>) Permeable soil; <span style=\" font-weight:600;\">B</span>) Semi-permeable soil; <span style=\" font-weight:600;\">C</span>) Almost impermeable soil</p></body></html>", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("RunoffCoefficient", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("RunoffCoefficient", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("RunoffCoefficient", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("RunoffCoefficient", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("RunoffCoefficient", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("RunoffCoefficient", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("RunoffCoefficient", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("RunoffCoefficient", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("RunoffCoefficient", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("RunoffCoefficient", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("RunoffCoefficient", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("RunoffCoefficient", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("RunoffCoefficient", "13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("RunoffCoefficient", "14", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("RunoffCoefficient", "15", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("RunoffCoefficient", "16", None))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("RunoffCoefficient", "17", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RunoffCoefficient", "Land use", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RunoffCoefficient", "A", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RunoffCoefficient", "B", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RunoffCoefficient", "C", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("RunoffCoefficient", "Barbecho, áreas incultas y desnudas", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("RunoffCoefficient", "Cultivos:", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("RunoffCoefficient", "En hilera", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("RunoffCoefficient", "Legumbres o rotación de pradera", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("RunoffCoefficient", "Granos pequeños", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("RunoffCoefficient", "Pastizal (Porcentaje del suelo cubierto o pastoreo):", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("RunoffCoefficient", "Más del 75 % (Poco)", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("RunoffCoefficient", " 0.14", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("RunoffCoefficient", " 0.20", None))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("RunoffCoefficient", "Del 50 al 75 % (Regular)", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("RunoffCoefficient", " 0.20", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("RunoffCoefficient", "Menos del 50 % (Excesivo)", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("RunoffCoefficient", "Bosque:", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto más del 75 %", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("RunoffCoefficient", " 0.07", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("RunoffCoefficient", " 0.16", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto del 50 al 75 %", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("RunoffCoefficient", " 0.12", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("RunoffCoefficient", " 0.22", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto del 25 al 50 %", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("RunoffCoefficient", " 0.17", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("RunoffCoefficient", "Cubierto menos del 25 %", None))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("RunoffCoefficient", " 0.22", None))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("RunoffCoefficient", " 0.28", None))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("RunoffCoefficient", "Zonas urbanas", None))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("RunoffCoefficient", " 0.26", None))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("RunoffCoefficient", " 0.29", None))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("RunoffCoefficient", " 0.32", None))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("RunoffCoefficient", "Caminos", None))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("RunoffCoefficient", " 0.27", None))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("RunoffCoefficient", " 0.30", None))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("RunoffCoefficient", " 0.33", None))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("RunoffCoefficient", "Pradera permanente", None))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("RunoffCoefficient", " 0.18", None))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("RunoffCoefficient", " 0.24", None))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("RunoffCoefficient", "0.30", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("RunoffCoefficient", "Annual precipitation [mm]:", None))
        self.label_4.setText(_translate("RunoffCoefficient", "Runoff coefficient value:", None))

