# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimpleDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimpleDesign(object):
    def setupUi(self, SimpleDesign):
        SimpleDesign.setObjectName(_fromUtf8("SimpleDesign"))
        SimpleDesign.resize(423, 236)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SimpleDesign)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(SimpleDesign)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRunoff = QtGui.QWidget()
        self.tabRunoff.setObjectName(_fromUtf8("tabRunoff"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabRunoff)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tabRunoff)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runoff = QtGui.QLineEdit(self.tabRunoff)
        self.runoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runoff.setObjectName(_fromUtf8("runoff"))
        self.horizontalLayout.addWidget(self.runoff)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.tabRunoff)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.runoffRationalFormula = QtGui.QPushButton(self.tabRunoff)
        self.runoffRationalFormula.setObjectName(_fromUtf8("runoffRationalFormula"))
        self.gridLayout_3.addWidget(self.runoffRationalFormula, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.runoffWaterMarks = QtGui.QPushButton(self.tabRunoff)
        self.runoffWaterMarks.setObjectName(_fromUtf8("runoffWaterMarks"))
        self.gridLayout_3.addWidget(self.runoffWaterMarks, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabRunoff, _fromUtf8(""))
        self.tabDimensions = QtGui.QWidget()
        self.tabDimensions.setObjectName(_fromUtf8("tabDimensions"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabDimensions)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.tabDimensions)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.weirLayersHeight = QtGui.QComboBox(self.tabDimensions)
        self.weirLayersHeight.setObjectName(_fromUtf8("weirLayersHeight"))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.weirLayersHeight.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.weirLayersHeight, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabDimensions)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        self.bodyLayersHeight = QtGui.QComboBox(self.tabDimensions)
        self.bodyLayersHeight.setObjectName(_fromUtf8("bodyLayersHeight"))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.bodyLayersHeight.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.bodyLayersHeight, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(self.tabDimensions)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.abutmentEqual = QtGui.QRadioButton(self.groupBox)
        self.abutmentEqual.setChecked(True)
        self.abutmentEqual.setObjectName(_fromUtf8("abutmentEqual"))
        self.verticalLayout_6.addWidget(self.abutmentEqual)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.abutmentCustom = QtGui.QRadioButton(self.groupBox)
        self.abutmentCustom.setObjectName(_fromUtf8("abutmentCustom"))
        self.horizontalLayout_3.addWidget(self.abutmentCustom)
        self.abutmentValue = QtGui.QLineEdit(self.groupBox)
        self.abutmentValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abutmentValue.sizePolicy().hasHeightForWidth())
        self.abutmentValue.setSizePolicy(sizePolicy)
        self.abutmentValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.abutmentValue.setObjectName(_fromUtf8("abutmentValue"))
        self.horizontalLayout_3.addWidget(self.abutmentValue)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabDimensions, _fromUtf8(""))
        self.tabWeir = QtGui.QWidget()
        self.tabWeir.setObjectName(_fromUtf8("tabWeir"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWeir)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabWeir)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.weirLenght = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirLenght.sizePolicy().hasHeightForWidth())
        self.weirLenght.setSizePolicy(sizePolicy)
        self.weirLenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirLenght.setObjectName(_fromUtf8("weirLenght"))
        self.gridLayout.addWidget(self.weirLenght, 0, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabWeir)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.weirCoefficient = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirCoefficient.sizePolicy().hasHeightForWidth())
        self.weirCoefficient.setSizePolicy(sizePolicy)
        self.weirCoefficient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirCoefficient.setObjectName(_fromUtf8("weirCoefficient"))
        self.gridLayout.addWidget(self.weirCoefficient, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 3, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabWeir)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.waterLevel = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterLevel.sizePolicy().hasHeightForWidth())
        self.waterLevel.setSizePolicy(sizePolicy)
        self.waterLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.waterLevel.setObjectName(_fromUtf8("waterLevel"))
        self.gridLayout.addWidget(self.waterLevel, 2, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 2, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabWeir)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.weirHeight = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirHeight.sizePolicy().hasHeightForWidth())
        self.weirHeight.setSizePolicy(sizePolicy)
        self.weirHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirHeight.setObjectName(_fromUtf8("weirHeight"))
        self.gridLayout.addWidget(self.weirHeight, 3, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 3, 3, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabWeir)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.weirLayers = QtGui.QLineEdit(self.tabWeir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weirLayers.sizePolicy().hasHeightForWidth())
        self.weirLayers.setSizePolicy(sizePolicy)
        self.weirLayers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weirLayers.setObjectName(_fromUtf8("weirLayers"))
        self.gridLayout.addWidget(self.weirLayers, 4, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 4, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tabWeir, _fromUtf8(""))
        self.tabStructural = QtGui.QWidget()
        self.tabStructural.setObjectName(_fromUtf8("tabStructural"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabStructural)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_10 = QtGui.QLabel(self.tabStructural)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.specWater = QtGui.QLineEdit(self.tabStructural)
        self.specWater.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.specWater.setObjectName(_fromUtf8("specWater"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.specWater)
        self.label_11 = QtGui.QLabel(self.tabStructural)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.specRock = QtGui.QLineEdit(self.tabStructural)
        self.specRock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.specRock.setObjectName(_fromUtf8("specRock"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.specRock)
        self.label_12 = QtGui.QLabel(self.tabStructural)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.frictionFactor = QtGui.QLineEdit(self.tabStructural)
        self.frictionFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionFactor.setObjectName(_fromUtf8("frictionFactor"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frictionFactor)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tabStructural, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SimpleDesign)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.runoff)
        self.label_2.setBuddy(self.runoffRationalFormula)
        self.label_7.setBuddy(self.weirLayersHeight)
        self.label_8.setBuddy(self.bodyLayersHeight)
        self.label_3.setBuddy(self.weirLenght)
        self.label_4.setBuddy(self.weirCoefficient)
        self.label_6.setBuddy(self.waterLevel)
        self.label_5.setBuddy(self.weirHeight)
        self.label_9.setBuddy(self.weirLayers)

        self.retranslateUi(SimpleDesign)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SimpleDesign.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SimpleDesign.reject)
        QtCore.QMetaObject.connectSlotsByName(SimpleDesign)

    def retranslateUi(self, SimpleDesign):
        SimpleDesign.setWindowTitle(_translate("SimpleDesign", "Simple Design", None))
        self.label.setText(_translate("SimpleDesign", "<html><head/><body><p>Runoff &amp;value [m<span style=\" vertical-align:super;\">3</span> s<span style=\" vertical-align:super;\">-1</span>]:</p></body></html>", None))
        self.label_2.setText(_translate("SimpleDesign", "Methods for runoff calculation:", None))
        self.runoffRationalFormula.setText(_translate("SimpleDesign", "Rational &formula", None))
        self.runoffWaterMarks.setText(_translate("SimpleDesign", "&High Water Marks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRunoff), _translate("SimpleDesign", "&Runoff", None))
        self.label_7.setText(_translate("SimpleDesign", "&Weir layers height [m]:", None))
        self.weirLayersHeight.setItemText(0, _translate("SimpleDesign", "0.15", None))
        self.weirLayersHeight.setItemText(1, _translate("SimpleDesign", "0.20", None))
        self.weirLayersHeight.setItemText(2, _translate("SimpleDesign", "0.30", None))
        self.weirLayersHeight.setItemText(3, _translate("SimpleDesign", "0.50", None))
        self.weirLayersHeight.setItemText(4, _translate("SimpleDesign", "1.00", None))
        self.label_8.setText(_translate("SimpleDesign", "&Dam body layers height [m]:", None))
        self.bodyLayersHeight.setItemText(0, _translate("SimpleDesign", "0.15", None))
        self.bodyLayersHeight.setItemText(1, _translate("SimpleDesign", "0.20", None))
        self.bodyLayersHeight.setItemText(2, _translate("SimpleDesign", "0.30", None))
        self.bodyLayersHeight.setItemText(3, _translate("SimpleDesign", "0.50", None))
        self.bodyLayersHeight.setItemText(4, _translate("SimpleDesign", "1.00", None))
        self.groupBox.setTitle(_translate("SimpleDesign", "Abutments", None))
        self.abutmentEqual.setText(_translate("SimpleDesign", "Abutment equal to layers height", None))
        self.abutmentCustom.setText(_translate("SimpleDesign", "Custom value [m]:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDimensions), _translate("SimpleDesign", "&Dimensions", None))
        self.label_3.setText(_translate("SimpleDesign", "&Lenght [m]:", None))
        self.label_4.setText(_translate("SimpleDesign", "&Coefficient:", None))
        self.weirCoefficient.setText(_translate("SimpleDesign", "1.45", None))
        self.label_6.setText(_translate("SimpleDesign", "W&ater level [m]:", None))
        self.label_5.setText(_translate("SimpleDesign", "&Height [m]:", None))
        self.label_9.setText(_translate("SimpleDesign", "La&yers:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWeir), _translate("SimpleDesign", "&Weir", None))
        self.label_10.setText(_translate("SimpleDesign", "<html><head/><body><p>Specific weight of water with sediment [t m<span style=\" vertical-align:super;\">-3</span>]:</p></body></html>", None))
        self.specWater.setText(_translate("SimpleDesign", "1.2", None))
        self.label_11.setText(_translate("SimpleDesign", "<html><head/><body><p>Specific weight of rock [t m<span style=\" vertical-align:super;\">-3</span>]:</p></body></html>", None))
        self.specRock.setText(_translate("SimpleDesign", "2.4", None))
        self.label_12.setText(_translate("SimpleDesign", "Rock on rock friction factor:", None))
        self.frictionFactor.setText(_translate("SimpleDesign", "0.75", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStructural), _translate("SimpleDesign", "&Structural Analysis", None))

